### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by bam-ftw** [paxel/lintstone#4]
https://github.com/paxel/lintstone/blob/59cf350156de8964014bc92710ce4c2acf692d91/src/test/java/paxel/lintstone/api/AdderActor.java#L22

Should be `" but got " + num`

https://github.com/paxel/lintstone/blob/59cf350156de8964014bc92710ce4c2acf692d91/src/test/java/paxel/lintstone/api/AdderActor.java#L37

Typo in "Acter "

**Comment by paxel** [comment]
cool. thanks for the review. will fix it asap.

**Comment by paxel** [comment]
pfychsed
